name: 'Post MD as Slack Post'
description: 'Convert a markdown file into'
author: 'donovan.fournier'
inputs:
  input-md:
    required: true
    description: 'Path to the markdown file'
  slack-token:
    required: true
    description: 'Slack Token of an app with the access to your channel'
  slack-channel:
    required: true
    description: 'ID/Name of the channel where you want to post your update'
runs:
  using: 'node16'
  main: 'dist/index.js'
